version: '3.8'
services:
  elasticsearch:
    image: "RobertRM/docker-elasticsearch-arm64:$ELK_VERSION"
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
volumes:
  data01:
networks:
  elastic:
    driver: overlay
